# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.14"]

    steps:
    - uses: actions/checkout@v7
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip dependencies
      uses: actions/cache@v6
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      id: flake8
      continue-on-error: true
      run: |
        # Stop the build if there are Python syntax errors or undefined names.
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Any remaining Flake8 error also fails the workflow.
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

    - name: Check if 'Lint with flake8' step failed
      if: steps.flake8.outcome != 'success'
      run: |
        echo "flake8 fails"
        exit 1
    
    - name: Test with pytest
      run: |
        # pytest
        echo "No tests implemented yet."
